@startuml
title UML Entreprise de vente

class Produit {
  numeroDeSerie : integer {key}
  prixAffiche : float
  reference : string
  prixReference : float
  description : string
  consommation : date
  categorie: string
  sousCategorie: string
  extensionGarantie : boolean
}

class Fournisseur {
	nom : string {key}
}

Fournisseur "1" -- "*" Produit : fourni >


class Facture {
  numeroFacture : integer {key}
  total : float 
}


class Client { 
  nom : string {key}
  prenom : string {key}
  dateNaissance : string {key}
  adresseMail : string
}
Facture "1" -- "1..*" Client : paye <

Facture "1" -- "*" Produit : contient >

class Personnel {
  idPersonnel: integer {key}
  service : ['Vente', 'Réparation', 'Achat', 'Après vente' ]
}


Personnel "1" -- "*" Facture : réalise >
Personnel "1" -- "*" TicketPriseEnCharge : crée >
Personnel "1" -- "*" BonDeCommande : crée >

class TicketPriseEnCharge {
  numeroSerieDuProduit : integer {key}
  date : string 
}

class BonDeCommande {
  referenceProduit : integer {key}
  quantite : integer
}


Achat "1" -- "1" BonDeCommande : concerne 

class Achat {
  prixUnitaire : float
  quantite : integer
}

class Reparation  {
  tempsPassé : float {key}
  materielUtilisé : string
}

class Reprise  {
  contre-partie : string
}


note bottom of TicketPriseEnCharge
    concerne Reparation XOR concerne Reprise
end note
TicketPriseEnCharge "1" -- "0..1" Reparation : concerne >
Reparation "1" -- "1" Facture : donne lieu >
TicketPriseEnCharge "1" -- "0..1" Reprise : concerne >
Reprise "1" -- "1" Facture : donne lieu >

Facture "1" -- "1" Vente : donne lieu <
class Vente  {
  installationRequise : boolean 
}


@enduml
